### PR TITLE
Adjust license links

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Broken links for license (the actual badges won't work until PyPI publication, of course)

### CODE REVIEW

**Review by garrettmflynn — COMMENTED** [review]
While multi-word packages are imported in `tqdm_publisher` style or a shortened name, they're commonly named as `tqdm-publisher`  (e.g. scikit-image, which uses `skimage` to import).

Is there a different convention that I'm missing here that you're following to rename the package?

**Comment by CodyCBakerPhD** [comment]
I'm matching the Python import style to the PyPI package, which is always a slight annoyance with these kinds of things

You're right that there's historical convention for the dashes, but there's many places where dashes aren't allowed, and hardly any where underscores aren't. I'm unaware of any technical reason why dashes are common for older packages, aside from the precedence that someone did it first and everyone copied the pattern. I'd personally rather everything be standard and stick to the same character in all cases, since there are technical reasons prohibiting dashes in some but not all cases

The overall preference otherwise is to avoid the question entirely and not use either character, instead using only a single word for the project, but since this is an extension of an existing package it seems better to keep as two words for findability

**Comment by CodyCBakerPhD** [comment]
Also the sklearn alias, while yes is possible to alias many things on the PyPI end, is a source of much confusion to new Python users and a potential delay even to veterans that forget about it

**Review by garrettmflynn — APPROVED** [review]
Understood. Thank you for the clarification :)

**Pull request merged**
