### PR TITLE
Trigger CI; remove minor comments; also run pre-commit

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Mostly testing the CI here

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Just so you're familiar with the CHANGELOG CI notification, it's really just there as a 'reminder' - the CHANGELOG doesn't actually have to be updated on every minor PR, only if there's an important bug fix or new feature

**Comment by CodyCBakerPhD** [comment]
Oh no, the codecov bot automatically showed up lol

What are you opinions about it? Are the CI reports for patch/project coverage differences useful?

**Comment by garrettmflynn** [comment]
I'm not super familiar with referring to Codecov reports. I understand the difference between project and patch reports—though I can't say at present whether the difference is useful for me personally.

What is your experience with this?

**Comment by CodyCBakerPhD** [comment]
> What is your experience with this?

Generally I find it pretty annoying

The one place it's useful is on the projects where coverage % is an actual milestone so you want to be able to deny a PR on the grounds it decreases coverage

I can disable the 2 CI in a follow-up; the actual bot reports summary diffs without it being a visible red X on the actions, which is a nice glance

**Review by garrettmflynn — APPROVED** [review]
Ah sure. Otherwise this looks great!

**Pull request merged**
