### PR TITLE
Improve parallel demo

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
WIP improving readability of the demo code for the parallel case

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn I'm trying to run the demo's on Windows

First I ran into trouble because the entrypoint wasn't working property; I fixed that but it does seem to require it to be packaged inside the main module

Second was how the non-parallel website was being automatically opened

However, I am still unable to run the parallel demo; it says that it serves it on local host 8000, and when I go there I see the entire filesystem for the git repo, but then it says 'file not found' (probably because of me moving things around) but I wasn't able to find anything in the client/server.py code to indicate where the path might be

Could you help get the parallel demo working on this branch?

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Also also, on a separate branch, could you outright refactor the non-parallel demo to patch the strategy of the second one?

All the extra threading stuff / ProgressHandler makes it really complicated to tell what's going on and how to use our class in a realistic setting; in particular the simulated progress bar I noticed is actually only iterating based on the randomness of when the downstream workers are being called (each task takes 0-5 seconds, 100,000 tasks, but entire bar is done filling in under 5 seconds), rather than the usual intuition of each iteration of a task taking the specified amount of time in a synchronous fashion

**Comment by garrettmflynn** [comment]
So this refactor has a number of issues that made debugging difficult on your end.

I was using `subprocess.Popen` for the clients instead of `subprocess.run` because these Python scripts are blocking, so the first one run is the _only_ one run in the latter case. As such, your refactor stops when the client is executed (which doesn't import the package), which appears to have fixed the entrypoint issue but has actually blocked execution of that part of the code. 

Similarly, the demo isn't working because the server can never open. When you see `Serving HTTP on 8080`, this is the basic HTTP *server* (acting as a "client" of sorts to receive messages from the TQDMPublisher, though we can discuss how to actually name these files moving forward) which has only been configured to handle `POST` requests of the TQDM information.

Based on this, do we want to rollback the [move demo inside to fix entrypoint](https://github.com/catalystneuro/tqdm_publisher/pull/37/commits/bf595cd3ce07db9120e3ee2dd6a2439544ff1ab8) commit so we can update the execution strategy with a more informed approach?

**Comment by CodyCBakerPhD** [comment]
> However, I am still unable to run the parallel demo; it says that it serves it on local host 8000, and when I go there I see the entire filesystem for the git repo, but then it says 'file not found' (probably because of me moving things around) but I wasn't able to find anything in the client/server.py code to indicate where the path might be

> So this refactor has a number of issues that made debugging difficult on your end.

Sorry I should have clarified; I was unable to run the parallel-demo on the `parallel-tests` branch because the entrypoint was not recognized (so it didn't even hit the lines that would have triggered anything to try to run)

What I then did was move it inside the package like mentioned, which allows it to recognize the entrypoint but that seemed to have changed some other file location reference

> Based on this, do we want to rollback the [move demo inside to fix entrypoint](https://github.com/catalystneuro/tqdm_publisher/pull/37/commits/bf595cd3ce07db9120e3ee2dd6a2439544ff1ab8) commit so we can update the execution strategy with a more informed approach?

The entrypoint itself was not registered on my system without that (was not be able to find the `demo` module)

**Comment by garrettmflynn** [comment]
Ah I forgot to post that if you install the package, you can run the demos. That was a quick workaround on my end

The README notes to install from PyPi, but I'd do an editable installation.

All of the usage issues stem from this choice, as the import is from tqdm_publisher, not a file in the project

**Comment by CodyCBakerPhD** [comment]
> Ah I forgot to post that if you install the package, you can run the demos. That was a quick workaround on my end

That's what I'm talking about 😆 I'm also proposing removing the standalone file execution to make it clear this is the only/intended way to run the demos

**Comment by CodyCBakerPhD** [comment]
> The README notes to install from PyPi

I'd like to make sure it works locally before releasing it; ideally, it should work in either case, but if anything there might be extra complications might happen during build wheel and upload (such as manifest issues)

**Comment by garrettmflynn** [comment]
Ah got it. I'd assumed this was the simple solution to your problems given that you hadn't attempted to manipulate the imports to something other than the `tqdm_publisher` package import.

As far as I can tell, all of the possible solutions require setting a relative import—something that I'm honestly not too sure how to use cleanly since every attempt generates `attempted relative import with no known parent package` no matter which location the demos sit in (aside from directly next to or up the tree from the `_publisher.py` file.

What are your suggestions on getting relative imports like this to behave appropriately?

**Comment by garrettmflynn** [comment]
> I'm also proposing removing the standalone file execution to make it clear this is the only/intended way to run the demos

Can you elaborate on what you mean by this? I'm not sure I'm following on which mode of execution to remove.

**Pull request closed without merging**
